/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module counter(
  input C,
  input RST,
  output Q_3,
  output Q_2,
  output Q_1,
  output Q_0
);
  wire Q_3_temp;
  wire Q_2_temp;
  wire Q_1_temp;
  wire Q_0_temp;
  wire s0;
  wire \~q_3n ;
  wire s1;
  wire \~q_2n ;
  wire s2;
  wire \~q_1n ;
  wire \~q_0n ;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  sg13g2_dfrbp_1 sg13g2_dfrbp_1_i0 (
    .CLK( C ),
    .D( s0 ),
    .Reset( RST ),
    .Q( Q_3_temp ),
    .\~Q ( \~q_3n  )
  );
  sg13g2_dfrbp_1 sg13g2_dfrbp_1_i1 (
    .CLK( C ),
    .D( s1 ),
    .Reset( RST ),
    .Q( Q_2_temp ),
    .\~Q ( \~q_2n  )
  );
  sg13g2_dfrbp_1 sg13g2_dfrbp_1_i2 (
    .CLK( C ),
    .D( s2 ),
    .Reset( RST ),
    .Q( Q_1_temp ),
    .\~Q ( \~q_1n  )
  );
  sg13g2_dfrbp_1 sg13g2_dfrbp_1_i3 (
    .CLK( C ),
    .D( \~q_0n  ),
    .Reset( RST ),
    .Q( Q_0_temp ),
    .\~Q ( \~q_0n  )
  );
  sg13g2_nand4_1 sg13g2_nand4_1_i4 (
    .A( Q_0_temp ),
    .B( Q_1_temp ),
    .C( Q_2_temp ),
    .D( \~q_3n  ),
    .Y( s3 )
  );
  sg13g2_nand3_1 sg13g2_nand3_1_i5 (
    .A( Q_0_temp ),
    .B( Q_1_temp ),
    .C( \~q_2n  ),
    .Y( s7 )
  );
  sg13g2_nand2_1 sg13g2_nand2_1_i6 (
    .A( \~q_0n  ),
    .B( Q_3_temp ),
    .Y( s4 )
  );
  sg13g2_nand2_1 sg13g2_nand2_1_i7 (
    .A( \~q_1n  ),
    .B( Q_3_temp ),
    .Y( s5 )
  );
  sg13g2_nand2_1 sg13g2_nand2_1_i8 (
    .A( \~q_2n  ),
    .B( Q_3_temp ),
    .Y( s6 )
  );
  sg13g2_nand2_1 sg13g2_nand2_1_i9 (
    .A( \~q_0n  ),
    .B( Q_2_temp ),
    .Y( s8 )
  );
  sg13g2_nand2_1 sg13g2_nand2_1_i10 (
    .A( \~q_1n  ),
    .B( Q_2_temp ),
    .Y( s9 )
  );
  sg13g2_nand2_1 sg13g2_nand2_1_i11 (
    .A( Q_0_temp ),
    .B( \~q_1n  ),
    .Y( s10 )
  );
  sg13g2_nand2_1 sg13g2_nand2_1_i12 (
    .A( \~q_0n  ),
    .B( Q_1_temp ),
    .Y( s11 )
  );
  sg13g2_nand4_1 sg13g2_nand4_1_i13 (
    .A( s3 ),
    .B( s4 ),
    .C( s5 ),
    .D( s6 ),
    .Y( s0 )
  );
  sg13g2_nand3_1 sg13g2_nand3_1_i14 (
    .A( s7 ),
    .B( s8 ),
    .C( s9 ),
    .Y( s1 )
  );
  sg13g2_nand2_1 sg13g2_nand2_1_i15 (
    .A( s10 ),
    .B( s11 ),
    .Y( s2 )
  );
  assign Q_3 = Q_3_temp;
  assign Q_2 = Q_2_temp;
  assign Q_1 = Q_1_temp;
  assign Q_0 = Q_0_temp;
endmodule
